src/carts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import (cart_home, cart_update, checkout_home, checkout_done_view)


urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

src/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (login_page,
                            register_page,
                            guest_register_view,
                            RegisterView,
                            LoginView,user_login)
from .views import home_page, about_page, contact_page
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from django.views.generic import TemplateView
from carts.views import cart_detail_api_view



urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', user_login, name='login'),
    #url(r'^login/$', login_page, name='login'),
    #url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    #url(r'^register/$', register_page, name='register'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^api/cart', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^products/', include('products.urls', namespace='product')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^admin/', admin.site.urls),
    # url(r'^products_fbv/$', product_list_view),
    # #url(r'^products/(?P<pk>\d+)$', ProductDetailView.as_view()),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # url(r'^products_fbv/(?P<pk>\d+)$', product_detail_view),
    # url(r'^feature/$', ProductFeaturedListView.as_view()),
    # url(r'^feature/(?P<pk>\d+)$', ProductFeaturedDetailView.as_view()),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

# Create your models here.
from products.models import Product
User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        print("Cart ID:", cart_id)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            print('Cart ID exists')
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    sub_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return (str(self.id))



def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    print(action)
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        print(instance.products.all())
        print(instance.total)
        products = instance.products.all()

        total = 0
        for x in products:
            total += x.price
        print("After:",total)
        if instance.sub_total != total:
            instance.sub_total = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.sub_total > 0:
        instance.total = Decimal(instance.sub_total) + Decimal(1.08)
    else:   
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, GuestForm
from .models import Cart
from orders.models import Order
from products.models  import Product
from billing.models import BillingProfile
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address
from django.http import JsonResponse


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
                    "id": x.id,
                    "url": x.get_absolute_url(),
                    "name":x.name,
                    "price":x.price
                 }
                 for x in cart_obj.products.all()]
    cart_data = {"products": products, "sub_total": cart_obj.sub_total, "total": cart_obj.total }
    return JsonResponse(cart_data)

# Create your views here.
def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    print ("COUNT: ", cart_obj.products.count())
    request.session['cart_total'] = cart_obj.products.count()
    return render(request, "carts/home.html", { "cart": cart_obj })


def cart_update(request):
    product_id = request.POST.get('product_id')
    print(request.POST)
    try:
        product_obj = Product.objects.get(id=product_id)
    except Product.DoesnotExist:
        print("Product is gone")
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    if product_obj in cart_obj.products.all():
        cart_obj.products.remove(product_obj)
        added = False
    else:
        cart_obj.products.add(product_obj)
        added = True
    request.session['cart_items'] = cart_obj.products.count()
    if (request.is_ajax()):
        print ("Ajax Request")
        json_data = {
            "added": added,
            "removed" : not added,
            "cartItemCount": cart_obj.products.count(),
        }
        return JsonResponse(json_data, status=200)
        #return JsonResponse({"message": "Error 400"}, status=400)
    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    print ("BILLING ID:", billing_address_id)
    print ("SHIPPING ID:", shipping_address_id)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile,cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]

        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "some check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            del request.session['cart_id']
            del request.session['cart_total']
        return redirect("cart:success")

    context = {
        "order": order_obj,
        "billing_profile": billing_profile,
        "login_form" : login_form,
        "guest_form" : guest_form,
        "address_form" : address_form,
        "address_qs" : address_qs,
    }
    return render(request, "carts/checkout.html", context)

def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})



    # user = request.user
    # billing_profile = None
    # login_form = LoginForm()
    # guest_form = GuestForm()
    # guest_email_id = request.session.get('guest_email_id')
    # print("Guest email id: ", guest_email_id)
    # if user.is_authenticated():
    #     'logged in user checkout; remember payment stuff'
    #     billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user, email=user.email)
    #     print("Billing Profile:", billing_profile, " | ", billing_profile_created)
    # elif guest_email_id is not None:
    #     'guest user checkout; auto reloads payment stuff'
    #     guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
    #     billing_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create(email=guest_email_obj.email)
    # else:
    #     pass

    #                                                            cart_obj)
        # order_qs = Order.objects.filter(billing_profile=billing_profile,cart = cart_obj, active=True)
        #
        # if order_qs.count() == 1:
        #     order_obj = order_qs.first()
        # else:
        #     order_obj = Order.objects.create(billing_profile=billing_profile, cart=cart_obj)

src/carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}

<div class='col-6 mx-auto py-5 text-center'>
  <h1 class='display-1'>Thank you for your order!!!</h1>
</div>

{% endblock %}

src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}
<!-- {{ order.order_id }} -- {{ order.cart }} -->

{% if not billing_profile %}

  <div class='row text-center'>
  <div class='col-12 col-md-6'>
    <p class='lead'>Login</p>
    {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
  </div>
  <div class='col-12 col-md-6'>
    Continue as Guest

    {% url "guest_register" as guest_register_url %}
    {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
  </div>
  </div>

{% else %}
    <!-- <P>Shipping Address: {{ order.shipping_address }}</p>
    <P>Billing Address: {{ order.billing_address }}</p> -->
    {% if not order.shipping_address %}
    <div class='row'>
      <div class='col-md-6 mx-auto col-10'>
        <p class='lead'>Shipping Address</p>
        <hr>
        {% url "checkout_address_create" as checkout_address_create_url %}
        {% include 'addresses/snippets/form.html'   with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_url address_type="shipping" %}
      </div>
      <div class='col-6 mx-auto'>
      {% if address_qs.exists %}
      {% url "checkout_address_reuse" as checkout_address_reuse_url %}
      {% include 'addresses/snippets/reuse-address.html' with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse_url address_type="shipping" %}
      {% endif %}
      </div>
    </div>
    {% elif not order.billing_address %}
    <div class='row'>
      <div class='col-md-6 mx-auto col-10'>
        <p class='lead'>Billing Address</p>
        <hr>
        {% url "checkout_address_create" as checkout_address_create_url %}
        {% include 'addresses/snippets/form.html'   with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_url address_type="billing" %}
      </div>
      <div class='col-6 mx-auto'>
      {% if address_qs.exists %}
      {% url "checkout_address_reuse" as checkout_address_reuse_url %}
      {% include 'addresses/snippets/reuse-address.html' with address_qs=address_qs next_url=request.build_absolute_uri action_url=checkout_address_reuse_url address_type="billing" %}
      {% endif %}
      </div>

    </div>
    {% else %}
    <div class='row'>
      <div class='col-6 mx-auto'>
        <H1>Finalize Checkout</h1>
        {% for product in order.cart.products.all %}
          {{ product.title }}
          {% if not forloop.last %}, {% endif %}
        {% endfor %}
        <p>Shipping Address: {{ order.shipping_address.get_address }}</p>
        <p>Billing Address: {{ order.billing_address.get_address }}</p>
        <p>Cart Total: {{ order.cart.total }}</p>
        <p>Shipping Total: {{ order.shipping_total }}</p>
        <p>Order Total: {{ order.total }}</p>
        <form method='POST' action=''> {% csrf_token %}
          <button type='submit' class='btn btn-success'>Checkout</button>
        </form>
      </div>

    </div>

    {% endif %}
{% endif %}

{% endblock %}

src/carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<H1>CART</h1>

{% if cart.products.exists %}
  <table class="table cart-table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product Price</th>
      </tr>
    </thead>
    <tbody class="cart-body">
        {% for product in cart.products.all %}
        <tr class="cart-products">
          <td scope="row">{{ forloop.counter }}</td>
          <td><a href='{{ product.get_absolute_url }}'>{{ product.name }}</a>
            {% include 'carts/snippets/remove-product.html' with product_id=product.id %}
              <!-- {% include 'products/snippet/update-cart.html' with product=product cart=cart in_cart=True%} -->
          </td>
          <td>{{ product.price }}</td>

        </tr>
        {% endfor %}

      <tr>
        <td colspan="2"></td>
        <td><b>Subtotal</b>$<span class="cart-subtotal">{{ cart.sub_total }}</span></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><b>Total</b>$<span class="cart-total">{{ cart.total }}</span></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td><a class='btn btn-success' href='{% url "cart:checkout" %}'>Checkout</td>
      </tr>

    </tbody>
  </table>
  <div class='cart-item-remove-form' style='display:none;'>
    {% include 'carts/snippets/remove-product.html' %}
  </div>
{% else %}
<p class='lead'>Cart is empty</p>
{% endif %}

{% endblock %}